version: '3.8'

services:
  api:
    image: node:23.10
    container_name: travel-paradise-api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "npm install && npm run dev"

  db:
    image: mariadb:10.7.8
    container_name: travel-paradise-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: